test(action): update the installation test

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -49,6 +49,10 @@ jobs:
         run: |
           docker exec ${CONTAINER_NAME} zsh -c "
               source ~/.zshrc
+              if [[ $? -ne 0 ]]; then
+                echo 'source ~/.zshrc failed'
+                exit 1
+              fi
               cat ~/.zshrc
               zpm -v
           "
